### ISSUE TITLE
More Components?

### ISSUE THREAD

**Issue by kentongray** [rui-cruz/Spark-Material#1]
Would love to see more components (list and grid specifically). Would you be interested in donations or project work on this? @kentonue if you want to talk!

**Comment by rui-cruz** [comment]
Hi kentongray,

About List we could extend base layouts to create groups and tiled groups.
Sure, all help are welcome.

**Comment by kentongray** [comment]
@rui-cruz anyway we can communicate via twitter dm or email? kgray [at the domain] iofficecorp.com is me

**Comment by rui-cruz** [comment]
Hi @kentongray , had you lost interest? I've added sliders #54544595888466 and error support to textinputs

Regards

**Comment by rui-cruz** [comment]
Added sliders #54544595888466
