### ISSUE TITLE
TabBar: Displace after maximize browser window and item click

### ISSUE THREAD

**Issue by olafkrueger** [rui-cruz/Spark-Material#15]
Steps to reproduce:
1) Maximize Browser window
2) Click one item (or mouse over)
3) TabBar/Items displace
4) After scrolling the TabBar is in place again

![tabbarresizebug](https://cloud.githubusercontent.com/assets/14052170/10579536/e0ef5626-7678-11e5-93f1-36772f14bccb.PNG)

**Comment by rui-cruz** [comment]
I can't reproduce this.

What browser / flashplayer version are you using? sounds something related to when flashplayer redraws.

**Comment by olafkrueger** [comment]
Seems I have to test by using different browsers in future.
Your're right, this issue only occurs with Firefox 41.0.2 (FlashPlayer 19,0,0,207).
With IE11 and Chrome 46.0.x  I also can't reproduce it.
So I think we can close this issue.

I hope I'll find some time to optimize the textara ;-)

Olaf
