### ISSUE TITLE
List Component

### ISSUE THREAD

**Issue by FiretronP75** [rui-cruz/Spark-Material#21]
Great progress! The one especially common component that isn't in here yet is the List component. Adding this Issue as a Feature Request. :)

**Comment by rui-cruz** [comment]
Hi @FiretronP75 ,

The List is already inside the dropdownlist. I basically changed the defaultItemRenderer to behave like a flat button.. 

Do you need any particular option that default List can't provide?

Regards and thank you for watching :+1:

**Comment by FiretronP75** [comment]
So if I use a normal Spark List and tell it to use your Spark Material DefaultItemRenderer, it will perfectly fit the look of your other skins?

**Comment by rui-cruz** [comment]
I think so.. give it a try and let me know ;)

All I did was: 

```
<s:DataGroup id="dataGroup" itemRenderer="spark.material.skins.DefaultItemRenderer">
    <s:layout>
        <s:VerticalLayout gap="0" horizontalAlign="contentJustify" requestedMinRowCount="1" requestedMaxRowCount="5"/>
        </s:layout>
</s:DataGroup> 
```

**Comment by FiretronP75** [comment]
Yes. Works on s:List also.
