### ISSUE TITLE
DropDown: Selected item lost its background color

### ISSUE THREAD

**Issue by olafkrueger** [rui-cruz/Spark-Material#8]
By clicking an item it lost its background color ("rollOverColor"):
![dropdownmissingbackgroundcolor](https://cloud.githubusercontent.com/assets/14052170/10427146/51eb9750-70e7-11e5-8fda-6f9a188c2db5.PNG)

After clicking an item the "rollOverColor" should still be there.
(Same behaviour like a button)

**Comment by rui-cruz** [comment]
Nice catch @ok-at-github, I fixed it by adding css markup "downColor" on commit 3a5c713bff272ba33cd7c6506772748dc55b72bb

**Comment by olafkrueger** [comment]
You've fixed it faster than I could think about a solution for this ;-)
I've just tested it and it just works but FlashBuilder 4.7. fires a warning:
![fb_4_7_stylewarning](https://cloud.githubusercontent.com/assets/14052170/10448750/24a7fab0-718f-11e5-80bd-002a956e31ae.PNG)
Do you've any idea?

**Comment by rui-cruz** [comment]
Yes, on Intellij don't throw that warning, I've formatted my pc and haven't installed FlashBuilder yet, and I'm missing some key features from FlashBuilder, like creating skins from template.. I tried to find the css markup to replace the "downColor" but I think there isn't! lol anyway I'll have to refactor that, and maybe we can create some custom css markup.

**Comment by olafkrueger** [comment]
Main issue is fixed.
